name: Terraform CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Terraform Lint, Init, Validate and Plan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Terraform - infra and deploy
    - name: Terraform Lint
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ~1.0
        tf_actions_subcommand: fmt
        tf_actions_working_dir: infra
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ~1.0
        tf_actions_subcommand: init
        tf_actions_working_dir: infra
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: $AWS_REGION

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ~1.0
        tf_actions_subcommand: validate
        tf_actions_working_dir: infra
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ~1.0
        tf_actions_subcommand: plan
        tf_actions_working_dir: infra
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: $AWS_REGION
