name: Terraform Deploy
on:
  workflow_dispatch:
    inputs:
      terraform_version:
        description: Terraform Version
        default: '1.0.0'
        required: false
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  AWS_REGION: us-east-1

jobs:
  deploy-infrastructure:
    name: Plan and Apply
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ github.event.inputs.terraform_version }}
        tf_actions_subcommand: plan -out infra.tfplan
        tf_actions_working_dir: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: $AWS_REGION

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ github.event.inputs.terraform_version }}
        tf_actions_subcommand: apply infra.tfplan
        tf_actions_working_dir: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: $AWS_REGION
